eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8767

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: eshop-datalink-service